---
version: "3.8"

services:
  app:
    container_name: thumbnail_getter_app
    image: thumbnail_getter:latest
    build:
      context: ./docker
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/code/
    ports:
      - "${APP_PORT:-8000}:8000"
