---
version: "3.8"

services:
  app:
    container_name: thumbnail_getter_app
    image: thumbnail_getter:latest
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/code/
